### ISSUE TITLE
Adapt the name of the author of the email

### ISSUE THREAD

**Issue by bepolymathe** [hogmoff/thunderbird-obsidian-export#1]
Hi, 

 Thank you again for this plugin which is essential for me on a daily basis.  I would simply like to make an adaptation that I can't find, probably because I'm bad at regex... 

 Currently the insertion of the author's name appears on the form `"FirstName Name" <Name@provider.net>` 

In general this is not a bad choice but when we want to insert this field in the YAML metadata it produces an error because Obsidian does not know how to read it.  It would probably be possible to use a formula to get `FirstName Name` instead?

**Comment by hogmoff** [comment]
Hi, 

to remove a substring between two characters try this string in 

Properties->Note->Trim author

<.*?>

![image](https://github.com/hogmoff/thunderbird-obsidian-export/assets/66696737/c68042a6-7eb5-47b3-8f11-2cf2b5e4da41)
