### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by bepolymathe** [hogmoff/thunderbird-obsidian-export#2]
Hi @hogmoff 

Thank you again for this plugin that I use every day and which is very useful.  I have an additional request.  I also use thunderbird for RSS feeds and I would like to be able to capture certain articles in the same way as emails in Obsidian. 

Currently, the plugin tries to capture the entire html code which causes problems quite often.  Do you think it would be possible to keep only the summary as content... or even to have a dedicated template for the feeds?

**Comment by hogmoff** [comment]
Hi, this is no issue. 
Please make a pull request and explain the extend with details. Only with good explanation and examples i can reproduce the problem.

**Comment by hogmoff** [comment]
Hi, this is no issue. 
Please make a pull request and explain the extend with details. Only with good explanation and examples i can reproduce the problem.
