### ISSUE TITLE
Link to message

### ISSUE THREAD

**Issue by bepolymathe** [hogmoff/thunderbird-obsidian-export#3]
Hi @hogmoff 

 A new idea.  I will find it very interesting to be able to return to the original message in thunderbird from obsidian.  Do you think it would be possible to integrate the possibility of a link to the message into the template? 

 It seems that other plugins offer it --» [https://github.com/KNHaw/ThunderbirdObsidianClipper](https://github.com/KNHaw/ThunderbirdObsidianClipper)
 I also use the [Cb-thunderlink](https://camiel.bouchier.be/en/cb_thunderlink) solution which allows you to have more durable links even if you move the messages into thunderbird. 

 What do you say ?

**Comment by hogmoff** [comment]
Hi, this is no issue. 
Please make a pull request and explain the extend with details. Only with good explanation and examples i can reproduce the problem.
